apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: camaras-trafico-com-tls
spec:
  secretName: camaras-trafico-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: camarastrafico.com
  dnsNames:
    - camarastrafico.com
    - www.camarastrafico.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - camarastrafico.com
          - www.camarastrafico.com